### ISSUE TITLE
Phoenix framework 1.3

### ISSUE THREAD

**Issue by kukula** [trenpixster/addict#128]
Any plans to support Phoenix 1.3?

**Comment by trenpixster** [comment]
🔜! Still didn't get to see what needs to be changed though :(

**Comment by atmd83** [comment]
I believe that when creating a model you need to add a Context (in phx 1.3), so you'd need that in the crud stuff
i.e. instead of App.User it would be Context.User

**Comment by dgoldie** [comment]
I'm playing with 1.3 and just tried addict.
The web directory is now named dev_app_web for an app named DevApp.
When I moved your files, I reached the login page.

With a Context of 'Accounts', the User schema is referenced by DevApp.Accounts.User
The import Ecto.Query is now in the Context and not in the schema.
That's as far as I've gotten so far.

**Comment by kukula** [comment]
Some work required  for "opinionated boilerplate", but I guess it's not an issue. Closing.
