### ISSUE TITLE
Use EEx templates for mails

### ISSUE THREAD

**Issue by c-rack** [trenpixster/addict#18]
As suggested by @jxs, we should use [EEx](http://elixir-lang.org/docs/stable/eex/) templates for mails.
- [ ] How should configuration look like? (multipart-mails, CC/BCC/header fields in general)
- [ ] I18N? (see also #13)
- [ ] Support for mail attachments / inline images?
- [ ] Support for non-mailgun mailers?

Opinions and PRs are welcome!

**Comment by jxs** [comment]
imho
1. configuration should have a couple of defaults, and be extendable
2. I18N yes, definitely if possible
3. unnecessary if templates are extendable
4. yes definitely 

what do you think @trenpixster ?

**Comment by trenpixster** [comment]
Nice one guys, EEx templates is definitely the way to go :+1:
Here are some thoughts:

1 - I'm thinking in turning everything regarding e-mail configurations into a hash, with sensible defaults, so we'd be able to have people configure e-mails - maybe even all configurations - like:

``` elixir
%{
  register: {
    template: Foo.Bar,
    from: "FooBar <foo@bar.com>",
    bcc: "analytics@bar.com"
    html: true
  },
  password_recover: {
    template: Foo.Baz,
    from: "FooBar <foo@bar.com>",
    html: true
  }
}
```

What do you think?
2 - This would be a great plus, just not sure the best way to implement it, still haven't looked at Linguist.
3 - I'm not foreseeing a case where an attachment is required?
4 - Yup, presentation layer should be agnostic of the underlying e-mail gateway.

**Comment by jxs** [comment]
agree with all :+1:

**Comment by c-rack** [comment]
Maybe we do not need to reinvent the wheel, as there is already a very promising Elixir library available:
https://github.com/kamilc/mailman

Unfortunately, it seems that is a little bit outdated. I will try to contact the author.

**Comment by trenpixster** [comment]
That's a nice library there. I wouldn't use it **instead** of the current solution, though:
- We could include the mail sending capability by defining it as a new mailer, `Addict.Mailers.SMTP`.
- Re-using the way it populates context data into the `eex` template on the `Addict.EmailGateway` would also be nice.

What do you think?

**Comment by jxs** [comment]
yeah, agree with you @trenpixster

**Comment by c-rack** [comment]
Quick update: thanks to @kamilc, [mailman](https://github.com/kamilc/mailman) is now available as hex package:
https://hex.pm/packages/mailman

**Comment by trenpixster** [comment]
#68
