### ISSUE TITLE
Update dependencies: Ecto and Phoenix

### ISSUE THREAD

**Issue by c-rack** [trenpixster/addict#27]
Currently, addict depends on:

``` elixir
{:phoenix, ">= 0.8.0"}
{:ecto, ">= 0.6.0"}
```

While current version of those packages are:

``` elixir
{:phoenix, ">= 0.10.0"}
{:ecto, ">= 0.9.0"}
```

I suggest to update the dependencies.

**Comment by trenpixster** [comment]
@c-rack It's always nice to have dependencies up to date, but I'd postpone this until we **really** need those dependencies bumped; the reason for this is that there may be people using Addict with an older version of Phoenix/Ecto and this kind of requirement might be really cumbersome for them :smile:

**Comment by bkochendorfer** [comment]
:+1: I'd like to use this library but it looks like I can't right now :).

**Comment by trenpixster** [comment]
@bkochendorfer sorry about that, what Phoenix and ecto versions are you running?

**Comment by bkochendorfer** [comment]
``` elixir
  defp deps do
    [{:phoenix, "~> 0.10.0"},
     {:phoenix_ecto, "~> 0.1"},
....
```

**Comment by bkochendorfer** [comment]
FYI, I was able to get this to work by vendoring the library locally and updating the dependencies. The only major difference from the example_app in this repo is adding the csrf_token to each post request. You can get this pretty easily in your template using `<%= get_csrf_token %>`.

**Comment by sajmoon** [comment]
Could the dependency be specified with > 0.8.0, thus allowing everybody to use it? I know it will fail due to csrf but that should be fixable.

**Comment by stevegraham** [comment]
Why do the dependencies need to be strict? If everything is following semver, surely the only issue is making sure major doesn't increment?

**Comment by trenpixster** [comment]
Yup, you're right guys. I'll update the semver accordingly. Thanks all for raising the issue!

**Comment by DanCouper** [comment]
Really minor, but could you push to Hex with the relaxed deps? Currently pulling direct from here, so not really an issue, but would be nice to just define deps as normal

**Comment by trenpixster** [comment]
Should be fixed on `hex.pm` v0.0.5 :smile:
