### ISSUE TITLE
Question: email address as username

### ISSUE THREAD

**Issue by schainks** [trenpixster/addict#33]
Does addict support allowing email address to be the user's username?  Can I override the username field or should I just both fields equal to the user's email address for now?

**Comment by trenpixster** [comment]
For the time being I'd say to use the same in both :smile: I'll be making some changes to the required fields scheme and their validation soon though, I'll ping you back on this issue when it's done.

**Comment by trenpixster** [comment]
@schainker #68 makes addict rely on e-mail now :smile:

**Comment by schainks** [comment]
<3 thanks @trenpixster!
