### ISSUE TITLE
Use for channel authentication

### ISSUE THREAD

**Issue by YayC** [trenpixster/addict#34]
Is there a way to adapt this for channel authentication? Maybe this would be easier if it was just storing a session token on the client, so I'm considering overriding the SessionInteractor's login / logout methods.

**Comment by trenpixster** [comment]
Hey @YayConnolly. That's a good question; I didn't yet do any kind of authentication via channels, but if your intent is to in fact login and logout via channels that seems to be the best approach in the current state. Not sure how you're thinking in storing the session itself, I believe channel doesn't expose a `connection`, right?

**Comment by williamgueiros** [comment]
https://github.com/phoenixframework/phoenix/pull/820

**Comment by trenpixster** [comment]
Nice! Thanks for the input @williamgueiros

**Comment by zmoshansky** [comment]
@YayConnolly Check out https://github.com/hassox/guardian. It addresses channel authentication using JWT. I'm actually quite happy to see addict just do basic user management well and then pair it with whatever token solution is desired.

**Comment by YayC** [comment]
Awesome, thanks @zmoshansky. I'll check out guardian. Seems like the Phoenix team is moving pretty quickly so hopefully the issue linked above gets merged soon.

**Comment by williamgueiros** [comment]
Token Auth is close :blue_heart: and start example 
https://github.com/phoenixframework/phoenix/issues/1063#issuecomment-125939907

**Comment by YayC** [comment]
Thanks for the heads up @williamgueiros !

**Comment by williamgueiros** [comment]
https://github.com/phoenixframework/phoenix_guides/pull/347#issuecomment-130316386

**Comment by trenpixster** [comment]
Closing this since we now have [this](http://hexdocs.pm/phoenix/Phoenix.Token.html) available.
