### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by phikes** [trenpixster/addict#36]
Hi, I find addict very useful, but had difficulties setting it up. **To enhance the experience for new developers I want to add to the documentation** (i.e. README). To start I need to **clarify** the following:
- When users perform a request to one of the addict route they get **a JSON response back**. What I understand is that addict encourages developers to make a request asynchronously with JS in the browser and handle the JSON there. Is that correct?

Otherwise great work, I will start some discussions on ideas I have ;-).

**Comment by trenpixster** [comment]
Hey @phikes! Yeah, that's basically the idea but it's not written in stone, you're more than welcome to suggest new ideas on how to handle the flow :smile:
