### ISSUE TITLE
Myapp.Addict.Controller is not available

### ISSUE THREAD

**Issue by jontonsoup** [trenpixster/addict#39]
Followed the directions for setup and am getting this error. Any ideas?

 *\* (UndefinedFunctionError) undefined function: Myapp.Addict.Controller.init/1 (module Myapp.Addict.Controller is not available)

Thanks,
Jon

**Comment by jontonsoup** [comment]
Turns out the generated router for phoenix and the directions are slightly off: 

Phoenix will generate:

```
scope "/", MyApp do 

end
```

**Comment by trenpixster** [comment]
Hey @jontonsoup, sorry for the delay;) It should be `Addict.Controller`.
