### ISSUE TITLE
Email Templates

### ISSUE THREAD

**Issue by Lazarus404** [trenpixster/addict#69]
Hi,

It would be good to get further explanation of the new email template requirements.  I've upgraded from 0.1 and now nothing quite works.  I've had to put the templates directly in the config, as the modules aren't found at the time of the config parsing.  Also, adding <%= email %> raises a token error:

```
** (exit) an exception was raised:
** (FunctionClauseError) no function clause matching in EEx.Tokenizer.tokenize/5
    (eex) lib/eex/tokenizer.ex:27: EEx.Tokenizer.tokenize(#Function<20.50752066/0 in :erl_eval.expr/5>, 1, [trim: false], [], [])
    (eex) lib/eex/compiler.ex:16: EEx.Compiler.compile/2
    (eex) lib/eex.ex:191: EEx.eval_string/3
    lib/addict/mailers/mail_sender.ex:11: Addict.Mailers.MailSender.send_register/1
```

as though email isn't known when parsing the template.  Any ideas?

Thanks,
Lee

**Comment by trenpixster** [comment]
Hey @Lazarus404, 

Sorry for the trouble with the breaking changes. Have you [checked this](https://github.com/trenpixster/addict/blob/master/docs/configs.md#e-mail-templates)? Does it help?

**Comment by Lazarus404** [comment]
No wholly.  I need to revisit.  Currently, I'm still updating my controller
functions so that they replace the ones supplied.  Mostly because when
registering / logging in, the user has more fields and relationships than a
simple email / pass.

It's all good, though :-)

**Comment by trenpixster** [comment]
Alright! If you feel there's something that Addict could provide to ease the pain with relationships feel free to speak out :)

I've added the concept of Post Hooks where you can do extra processing after an [action happens](https://github.com/trenpixster/addict/blob/master/configs.md#post-action-hooks) (maybe `post_login` and `post_register` are useful) and one other handle for [extra validations](https://github.com/trenpixster/addict/blob/master/configs.md#user-model-validation) that might also fit your flow, given you have relationships on the User model.

I'll close this issue for now, if you still have any issues with the e-mail templates after reading the docs please re-open it :+1:
