### ISSUE TITLE
Configuration won't work with exrm releases

### ISSUE THREAD

**Issue by smpallen99** [trenpixster/addict#77]
Your documentation says to put this in your configuration file:

```
post_login: &MyApp.PostLoginAction.log/3
```

This type of configuration won't work with exrm releases. You should change your implementation to use the following format: 

```
post_login: {MyApp.PostLoginAction, :log}
```

and use the following to run the callback:

```
{mod, fun} = Application.get_env :addict, :post_login
apply mod, fun, [arg1, arg2, arg3]
```

I've been burned with this probably a few times....

**Comment by trenpixster** [comment]
Ohhh, that explains it! Thanks @smpallen99! 👍
