### ISSUE TITLE
Add Mix tasks

### ISSUE THREAD

**Issue by trenpixster** [trenpixster/addict#9]
It'd be great to be able to auto-populate a Phoenix project with sensitive defaults through a mix task.
Something like
- `mix addict.gen.user` would generate the minimum bares user model.
- `mix addict.gen.email_templates` would generate the minimum bares email templates.

One added plus would be to do this in the project's namespace and also add the required keys to  `config.exs`.

**Comment by Anonyfox** [comment]
It would be awesome to just run something like `mix addict.init` and everything is set up for you with sane defaults, including model/migration, templates, mail-templates. I understand that this can't be _that easy_ like in meteor ("put your loginbuttons there and done!"), but this would be really cool to get started faster with phoenix.

**Comment by trenpixster** [comment]
#68
