### ISSUE TITLE
Guide to using within Json API app

### ISSUE THREAD

**Issue by simonh1000** [trenpixster/addict#91]
Hi, I am looking for guidance on whether/how I can use some of the library functions alone. I need to provide password reset functionality within the context of an (Elm) single page app.
Simon

**Comment by trenpixster** [comment]
Hey @simonh1000,

Sorry for the delay; I'd say you can create a new `route` and in the corresponding controller call something like: 

``` elixir
def reset_password(conn, %{"new_password" => new_password}) do
  # get the user and assign it to user
  Addict.Interactors.UpdateUserPassword.call(user, new_password)
  # return response 
end
```

**Comment by trenpixster** [comment]
@simonh1000 did this work for you? Closing it, but feel free to re-open if you still face any issues.
