### ISSUE TITLE
Customizable password encryption strategies

### ISSUE THREAD

**Issue by steveklebanoff** [trenpixster/addict#93]
As far as I can see, `Comeonin.Pbkdf2` is hard-coded in to be the only way to encrypt passwords.  It would be cool if there was a way to provide custom strategies for encrypting passwords. Use case: using `addict` to interact with a DB of users who had their passwords encrypted another way

**Comment by trenpixster** [comment]
Makes sense 👍

**Comment by trenpixster** [comment]
Closed via #94
