### ISSUE TITLE
Break dependencies in Phoenix 1.2

### ISSUE THREAD

**Issue by claudiojulioferraz** [trenpixster/addict#98]
$ mix deps.get
Running dependency resolution

Failed to use "poison" (version 2.2.0) because
  mailgun (version 0.1.0) requires ~> 1.3.1
  phoenix (version 1.2.0) requires ~> 1.5 or ~> 2.0
  Locked to 2.2.0 in your mix.lock

Failed to use "poison" (version 2.2.0) because
  mailgun (version 0.1.1) requires ~> 1.4.0
  phoenix (version 1.2.0) requires ~> 1.5 or ~> 2.0
  Locked to 2.2.0 in your mix.lock

Failed to use "poison" (version 2.2.0) because
  mailgun (version 0.1.2) requires ~> 1.4
  phoenix (version 1.2.0) requires ~> 1.5 or ~> 2.0
  Locked to 2.2.0 in your mix.lock

*\* (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock)

**Comment by aphillipo** [comment]
Hi there!  We are trying to use Addict in a Phoenix 1.2 project and coming up with some issues!

Any idea if these are going to be fixed - addict looks perfect for our needs!

**Comment by claudiojulioferraz** [comment]
Hello! I tried to fix the dependencies, but could not. I'm still learning how to program. I love libraries following the convention over configuration. It is the best paradigm design. If I want something other than the default, I go there and set up. Thank you for this excellent software. 

_Automatically translated._

**Comment by trenpixster** [comment]
@aphillipo @claudiojulioferraz thanks for bringing this up! I've been on a tight schedule but will tackle this next. 👍

**Comment by mdoza** [comment]
Mailgun is only allowing Poison ~> 2.0, which is one issue. I've submitted a PR over there to help get a step closer.

**Comment by denic** [comment]
Didn't try but will it help to use:

`{:poison, "~> 2.1", override: true}`

as the [phoenix documentation](http://www.phoenixframework.org/docs/sending-email) suggests?

**edit**

I can confirm it works after sticking the poison version but I also had to set the ecto version to the one requiered by phoenix.

**Comment by acrolink** [comment]
Any news on this?

**Comment by mdoza** [comment]
@acrolink not yet.

**Comment by trenpixster** [comment]
I've updated the code and it seems to be compatible with Phoenix 1.2, but I'm having some issues with Ecto 2.0 on my specs :(

**Comment by trenpixster** [comment]
Can you guys give it a go with the `master` branch? Kinda sucks to be a breaking change, but not seeing any way to work around it.
